#!/bin/bash

# A quick script to explicitly allow ssh connections in from the calling IP

set -eo pipefail

ssh_connection_array=($SSH_CONNECTION)
source=${ssh_connection_array[0]}
ufw allow to any app OpenSSH from "${1:-$source}"
