#!/bin/bash

# A quick script to explicitly allow ssh connections in from the calling IP

set -euo pipefail
err_report() {
    echo "errexit on line $(caller)" >&2
}
trap err_report ERR

die() {
    echo $2 >&2
    exit $1
}

SCRIPT_DIR=$(dirname $(readlink -f $0))

if [[ -f /opt/git/admin-tools/parse-opt.sh ]]; then
    # No short arguments
    declare -A PO_SHORT_MAP

    # All long arguments are lowercase versions of their corresponding envars
    declare -A PO_LONG_MAP
    PO_LONG_MAP["comment:"]="COMMENT"

    # parse command line options
    . /opt/git/admin-tools/parse-opt.sh
fi

if [[ ! $COMMENT ]]; then
    COMMENT="added by $0"
fi

if [[ $@ ]]; then
    for source in $@; do
        ufw allow to any app OpenSSH from "${source}" comment "${COMMENT}"
    done
elif [[ $SSH_CONNECTION ]]; then
    ssh_connection_array=($SSH_CONNECTION)
    ufw allow to any app OpenSSH from "${ssh_connection_array[0]}" comment "${COMMENT}"
else
    die 1 "No IPs supplied and could not guess connection details"
fi
