#!/bin/bash

set -e
CURL_FLAGS="-LSsf"

SOURCES_DIR=/etc/apt/sources.list.d

if [[ ! $3 ]]; then
  cat <<EOF
Usage: $0 REPO_NAME "REPO_CONFIG" GPGKEY_URL

A utility to safely add an APT repository with a GPG signing key, while 
avoiding the unsafe use of 'curl GPGKEY_URL | apt-key add -'

REPO_NAME is a unique local identifier for the repo.

REPO_CONFIG is the full description of the repo that should be added to the
sources.list file, e.g. "http://ftp.debian.org/debian stable main". Since
this will usually contain spaces, it should be enclosed in quotes.

GPGKEY_URL is a URL from which to download the signing key of the repo.

This tool implements the safe third-party repo method as described in
https://wiki.debian.org/DebianRepository/UseThirdParty
EOF
  exit 1
fi

REPO_NAME="$1"
REPO_CONFIG="$2"
GPGKEY_URL="$3"

SOURCES_FILE="$SOURCES_DIR/$REPO_NAME".list
GPGKEY_FILE="$SOURCES_DIR/.$REPO_NAME".gpg

if [[ -f $SOURCES_FILE || -f $GPGKEY_FILE ]]; then
  echo "Unable to create files; repo already configured!"
  exit 2
fi

cat <<EOF >$SOURCES_FILE
deb [signed-by=$GPGKEY_FILE] $REPO_CONFIG
EOF

TMPFILE=$(mktemp)
curl $CURL_FLAGS -o $TMPFILE $GPGKEY_URL
gpg --no-default-keyring --keyring=$GPGKEY_FILE --import $TMPFILE
# This might leave a backup file; clean it up
rm "$GPGKEY_FILE~" || echo -n
rm $TMPFILE

