#!/bin/bash

# A QAD script to upgrade from old versions of letsencrypt/certbot to certbot
# >=0.20 with directory-hooks

set -e

if [[ -d /etc/apt ]]; then
	if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]; then
	  apt-get update
	fi
    ! apt-cache show certbot | egrep -q "Version: 0\.[23456789]\d"
    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
        echo "Can't find certbot >=0.20"
        exit 1
    fi
    apt install certbot
elif [[ -d /etc/yum ]]; then
    ! yum list certbot | egrep -q "certbot\.noarch\s+0\.[23456789]\d"
    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
        echo "Can't find certbot >=0.20"
        exit 1
    fi
    yum install certbot
else
    echo "Distribution not supported!"
    exit 2
fi

if [[ ! -d /etc/letsencrypt/renewal-hooks/post ]]; then
    echo "Certbot did not create hook directory; aborting"
    exit 3
fi

if which letsencrypt >/dev/null ; then
    if [[ $(readlink $(which letsencrypt)) != "certbot" ]]; then
        echo "WARNING: /usr/bin/letsencrypt exists and is not a soft link to certbot"
    fi
fi

rm -rf /usr/local/bin/certbot-auto /usr/local/bin/letsencrypt /usr/local/share/letsencrypt /opt/eff.org || true
for i in $(ls /etc/cron.{daily,hourly,weekly,monthly}/letsencrypt 2>/dev/null); do
    mv $i $i.bak
    echo "Old letsencrypt cron-script moved to $i.bak"
done
if [[ -f /etc/cron.d/letsencrypt ]]; then
    mv /etc/cron.d/letsencrypt /root/letsencrypt.cron.bak
    echo "Old letsencrypt crontab moved to /root/letsencrypt.cron.bak"
fi

if [[ -f /etc/cron.d/certbot.dpkg-dist ]]; then
    # apt install must have been unable to update the certbot configfile,
    # probably because it was manually edited. We'll have none of that here!
    if [[ -f /etc/cron.d/certbot ]]; then
        mv /etc/cron.d/certbot /root/certbot.cron.bak
        echo "Old certbot crontab moved to /root/certbot.cron.bak"
    fi
    mv /etc/cron.d/certbot{.dpkg-dist,}
fi

if which nginx >/dev/null; then
    echo "/sbin/service nginx reload 2>&1 | logger -t certbot" > /etc/letsencrypt/renewal-hooks/post/nginx.sh
    chmod +x /etc/letsencrypt/renewal-hooks/post/nginx.sh
    echo "Created standard nginx reload post-hook"
elif which apache2ctl >/dev/null; then
    echo "/sbin/service apache2 reload 2>&1 | logger -t certbot" > /etc/letsencrypt/renewal-hooks/post/apache.sh
    chmod +x /etc/letsencrypt/renewal-hooks/post/apache.sh
    echo "Created standard apache2 reload post-hook"
fi

if [[ -f /etc/letsencrypt/renewal/*.sh ]]; then
    mv /etc/letsencrypt/renewal/*.sh /etc/letsencrypt/renewal-hooks/post/
    echo "Found post-hooks: " /etc/letsencrypt/renewal-hooks/post/*.sh
fi
