#!/bin/bash

# A script to wait for a list of URLs to come up

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
# shellcheck disable=SC1090
. "$SCRIPT_DIR/poshlib/poshlib.sh" || exit 1
use swine
use parse-opt

CURL_FLAGS=-SsfLk

[[ "${1:-}" ]] || die 1 "Usage: $0 <url>[,...] [<retries> [<retry_wait>]]"
URLS=$(tr , " " <<< "$1")

retries=${2:-30}
retry_wait=${3:-10}

for url in $URLS; do
  while
    err=0
    curl $CURL_FLAGS "$url" > /dev/null 2>&1 || err=$?
    # error 22 (unauthorised) counts as success in this context
    [[ $err != 0 && $err != 22 ]]
  do
    retries=$((retries-1))
    if [[ $retries -eq 0 ]]; then
        die 2 "Too many retries; aborting"
    fi
    echo -n "."
    sleep "$retry_wait"
  done
done
echo
exit 0
