#!/bin/bash

# A tool to automatically mitigate https://bugs.launchpad.net/ubuntu/+source/golang-github-docker-docker-credential-helpers/+bug/1794307
# by using the technique at https://github.com/docker/compose/issues/6023#issuecomment-419792269

set -euo pipefail

apt-get update
apt-get install -y pass
gpg --full-generate-key
keyid=$(gpg -K | awk '/^sec/ {print $2}')
pass init ${keyid#*/0x}
