#!/bin/bash

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
. "${SCRIPT_DIR}/poshlib/poshlib.sh" || exit 1
use swine

# Set up rkhunter. This should be called late in the installation process.

if [[ -d /etc/apt ]]; then
	APT=true
elif [[ -d /etc/yum ]]; then
	YUM=true
else
	echo "Distribution not supported!"
	exit -1
fi

# rkhunter is enabled automatically on centos, but not under apt
if [[ -f /etc/default/rkhunter ]]; then
  sed -i -e 's/^CRON_DAILY_RUN=.*$/CRON_DAILY_RUN="yes"/' /etc/default/rkhunter
  sed -i -e 's/^CRON_DB_UPDATE=.*$/CRON_DB_UPDATE="yes"/' /etc/default/rkhunter
  sed -i -e 's/^APT_AUTOGEN=.*$/APT_AUTOGEN="yes"/' /etc/default/rkhunter

  sed -i -e 's/^UPDATE_MIRRORS=.*$/UPDATE_MIRRORS=1/' /etc/rkhunter.conf
  sed -i -e 's/^MIRRORS_MODE=.*$/MIRRORS_MODE=0/' /etc/rkhunter.conf
  sed -i -e 's/^WEB_CMD=.*$/WEB_CMD=""/' /etc/rkhunter.conf
fi

rkhunter --update
rkhunter --propupd
rkhunter --check
