#!/bin/bash

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
. "${SCRIPT_DIR}/poshlib/poshlib.sh" || exit 1
use swine
use keyval

# Set up rkhunter. This should be called late in the installation process.

if [[ -d /etc/apt ]]; then
	APT=true
elif [[ -d /etc/yum ]]; then
	YUM=true
else
	echo "Distribution not supported!"
	exit -1
fi

# Fix up broken default APT configuration
APT_HIDDEN_DIRS=(/etc/.git /etc/.bzr /etc/.java)
APT_HIDDEN_FILES=(/etc/.gitignore /etc/.bzrignore /etc/.etckeeper /etc/.updated)
APT_SCRIPT_WHITELIST=(/usr/bin/lwp-request)

if [[ ${APT:-} ]]; then

    # rkhunter is enabled automatically on centos, but not under APT
    keyval-add /etc/default/rkhunter CRON_DAILY_RUN yes
    keyval-add /etc/default/rkhunter CRON_DB_UPDATE yes
    keyval-add /etc/default/rkhunter APT_AUTOGEN yes

    # rkhunter's default APT configuration is bad
    keyval-add /etc/rkhunter.conf UPDATE_MIRRORS 1
    keyval-add /etc/rkhunter.conf MIRRORS_MODE 0
    keyval-delete --comment /etc/rkhunter.conf WEB_CMD

    # rkhunter.conf supports cumulative definitions, use --multi
    for dir in "${APT_HIDDEN_DIRS[@]}"; do
        keyval-add --multi /etc/rkhunter.conf ALLOWHIDDENDIR "${dir}"
    done
    for file in "${APT_HIDDEN_FILES[@]}"; do
        keyval-add --multi /etc/rkhunter.conf ALLOWHIDDENFILE "${file}"
    done
    for script in "${APT_SCRIPT_WHITELIST[@]}"; do
        # rkhunter borks if SCRIPTWHITELIST references nonexistent files
        [[ ! -f "$script" ]] || keyval-add --multi /etc/rkhunter.conf SCRIPTWHITELIST "${script}"
    done

    # Allow root user without password (i.e. ssh pubkey)
    # If Mallory has a privileged ssh key, they can trivially escalate using
    # pam_ssh_agent_auth, so denying root login outright has minimal effect.
    #
    # This is the default under APT, so the parameter should be unset
    keyval-add /etc/rkhunter.conf ALLOW_SSH_ROOT_USER unset

elif [[ ${YUM:-} ]]; then

    # Allow root user without password (i.e. ssh pubkey)
    # If Mallory has a privileged ssh key, they can trivially escalate using
    # pam_ssh_agent_auth, so denying root login outright has minimal effect.
    keyval-add /etc/rkhunter.conf ALLOW_SSH_ROOT_USER without-password

fi

try rkhunter --update
if catch error && [[ "$error" != 2 ]]; then
    die $error "rkhunter failed to download updates"
fi
rkhunter --propupd
rkhunter --cronjob --report-warnings-only || true
