#!/bin/bash

# A QAD tool to fix the hostname of a remote server to match a given FQDN.

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
# shellcheck disable=SC1090
. "$SCRIPT_DIR/poshlib/poshlib.sh" || exit 1
use strict

[[ ${1:-} ]] || die 1 "Usage: $0 FQDN"
fqdn=$1
host=${fqdn%%.*}
oldhost=$(</etc/hostname)

echo "$host" > /etc/hostname
hostname "$host"
perl -pi -e "s/([ \t])${oldhost}(\.[[:alnum:]_.-]+([ \t]|$))/\\1${fqdn}\\3/g; s/([ \t])${oldhost}([ \t]|$)/\\1${host}\\2/g" /etc/hosts
