#!/bin/bash

# A toolkit to fix a broken linux boot
# This is the outer script, which should be called directly
# For safety, it assumes that it has been installed under /opt/git

# To use, first mount the root disk at e.g. /mnt
# Then run this script by its full path, e.g. /mnt/opt/git/admin-tools/fixboot

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck disable=SC1090,SC1091
. "$SCRIPT_DIR/poshlib/poshlib.sh" || exit 1
use strict
use utils

ROOT="${SCRIPT_DIR%/opt/git/*}"
[[ "$ROOT" != "$SCRIPT_DIR" ]] || exit 1
pushd "$ROOT" || exit 2

for dir in proc sys run dev dev/pts; do
    mount -o bind "/$dir" "$dir"
done

chroot . "$SCRIPT_DIR/fixboot-chroot"
