#!/bin/bash
set -e

# QAD script to test which disks grub is installed on

drives=$(ls /dev/nvme?n? /dev/sd[abcdefghijklmnopqrstuvwxyz] 2> /dev/null)

for drive in $drives; do
    echo -n "$drive "
    if dd bs=512 count=1 if=$drive 2>/dev/null | grep -q GRUB; then
        echo grub installed
    else
        echo GRUB NOT INSTALLED
    fi
done
