#!/bin/bash
set -e
shopt -s nullglob

# QAD script to test which disks grub is installed on

for drive in /dev/nvme?n? /dev/sd[abcdefghijklmnopqrstuvwxyz]; do
    echo -n "$drive "
    if dd bs=512 count=1 if=$drive 2>/dev/null | grep -q GRUB; then
        echo grub installed
    else
        echo GRUB NOT INSTALLED
    fi
done
