#!/bin/bash

# QAD script to install and configure libpam-ldap

if [[ -d /etc/apt ]]; then
	APT=true
	SUDO=sudo
elif [[ -d /etc/yum ]]; then
	YUM=true
	SUDO=wheel
else
	echo "Distribution not supported!"
	exit -1
fi

# Support headless installation
export DEBIAN_FRONTEND=noninteractive

# A *space-separated* list of LDAP URIs
LDAP_SERVERS="ldaps://pdc.example.com"
BASE_DN="dc=example,dc=com"

# A *newline-separated* list of sudoers to preseed
ADMIN_USERS="andgal Andrew Gallagher"

if [[ -f /etc/install-pam-ldap ]]; then
	. /etc/install-pam-ldap
fi
if [[ -f ~/.install-pam-ldap ]]; then
	. ~/.install-pam-ldap
fi

if [[ $APT ]]; then

  cat >/tmp/debconf-selections <<EOF
ldap-auth-config ldap-auth-config/ldapns/ldap_version select 3
ldap-auth-config ldap-auth-config/dblogin boolean false
ldap-auth-config ldap-auth-config/move-to-debconf boolean true
ldap-auth-config ldap-auth-config/ldapns/ldap-server string ${LDAP_SERVERS}
ldap-auth-config ldap-auth-config/ldapns/base-dn string ${BASE_DN}
ldap-auth-config ldap-auth-config/dbrootlogin boolean false
EOF

  debconf-set-selections /tmp/debconf-selections
  if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]; then
    apt-get update
  fi
  apt-get install -y libpam-ldap

elif [[ $YUM ]]; then

  yum -y install nss-pam-ldapd authconfig
  authconfig --enableldapauth --ldapserver="${LDAP_SERVER_LIST}" --ldapbasedn="${BASE_DN}" --enablerfc2307bis --disableldaptls --update

  # Unnecessary shit like this is why I use Debian.
  # https://serverfault.com/questions/437546/centos-openldap-cert-trust-issues
  echo "tls_cacertfile /etc/pki/tls/certs/ca-bundle.crt" >> /etc/nslcd.conf
  service nslcd restart

fi

IFS="
"
for i in $ADMIN_USERS; do
	userid="${i%% *}"
	realname="${i#* }"
	if [[ $APT ]]; then
		# We can and must do this on one line, else we get prompted
		adduser --disabled-password --gecos "${realname}" $userid
	elif [[ $YUM ]]; then
		# We can't do it on one line, but adduser doesn't complain
		adduser $userid
		usermod --lock $userid
		usermod --comment "${realname}" $userid
	fi
	usermod -aG ${SUDO} $userid
done
