#!/bin/bash

# QAD script to install and configure libpam-ldap

# Support headless installation
export DEBIAN_FRONTEND=noninteractive

# A *space-separated* list of LDAP URIs
LDAP_SERVERS="ldaps://ops.siren.io ldaps://mon1.siren.io"
BASE_DN="dc=siren,dc=io"

# A *newline-separated* list of sudoers to preseed
ADMIN_USERS="andgal Andrew Gallagher"

if [[ -f /etc/install-pam-ldap ]]; then
	. /etc/install-pam-ldap
fi
if [[ -f ~/.install-pam-ldap ]]; then
	. ~/.install-pam-ldap
fi

cat >/tmp/debconf-selections <<EOF
ldap-auth-config ldap-auth-config/ldapns/ldap_version select 3
ldap-auth-config ldap-auth-config/dblogin boolean false
ldap-auth-config ldap-auth-config/move-to-debconf boolean true
ldap-auth-config ldap-auth-config/ldapns/ldap-server string ${LDAP_SERVERS}
ldap-auth-config ldap-auth-config/ldapns/base-dn string ${BASE_DN}
ldap-auth-config ldap-auth-config/dbrootlogin boolean false
EOF

debconf-set-selections /tmp/debconf-selections
apt install -y libpam-ldap

IFS="
"
for i in $ADMIN_USERS; do
	userid=${i%% *}
	realname=${i#* }
	adduser --disabled-password --gecos $realname $userid
	usermod -aG sudo $userid
done
