#!/bin/bash

# QAD script to install and configure ntp

timedatectl set-timezone Etc/UTC

if [[ -d /etc/apt ]]; then
    # Support headless installation
    export DEBIAN_FRONTEND=noninteractive
    export NEEDRESTART_SUSPEND=y
    
    if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]; then
        apt-get update
    fi
    apt install -y ntp
elif [[ -d /etc/yum ]]; then
    yum -y --setopt=skip_missing_names_on_install=False install ntp
else
    echo "Distribution not supported!"
    exit -1
fi
