#!/bin/bash
#
# A script to bulk operate on all your git repos
# Searches under PWD for git repos

for gitdir in $(find . -type d -name .git); do
    repo=$(dirname $gitdir)
    echo -e "------------------------"
    pushd $repo > /dev/null
    pwd
    echo -e "------------------------"
    git $*
    popd > /dev/null
    echo
done
