#!/bin/bash
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
. $SCRIPT_DIR/poshlib/poshlib.sh

# This is just a wrapper script for the vercomp() function

USEPATH="$USEPATH:$SCRIPT_DIR"
use vercomp
vercomp "$@"
