#!/bin/bash
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
# shellcheck disable=SC1090
. "$SCRIPT_DIR/poshlib/poshlib.sh" || exit 1

# This is just a wrapper script for the vercomp() function

use-from .
use vercomp
vercomp "$@"
