#!/bin/bash
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
. $SCRIPT_DIR/poshlib/poshlib.sh || exit 1
use-from "$SCRIPT_DIR"
use swine
use yaml-elastic

if [[ $1 == "-r" ]]; then
    yaml-replace "$2" "$3"
else
    yaml-extract "$1" "$2"
fi
