#!/bin/bash

# A QAD script to enable new zerotier hosts via the zerotier API
# $1 is the ansible host or group name
# $2 is the ztsetup config file that was used on each host

set -eo pipefail

CURL_ARGS=-SsfL
if [[ ! $ZT_TOKEN_FILE ]]; then
    ZT_TOKEN_FILE=/root/.zerotier-token
fi
inventory="$1"
. "$2"

# NETWORKS is a comma-separated list of zerotier networks to join
# Comments are delimited by colons
#NETWORKS="8056c2e21c000001:world"
# It can also be newline-separated, and/or with space-delimited comments
#NETWORKS=$'8056c2e21c000001 world\n0000000000000000 nowhere'

# canonicalise format
NETWORKS=$(echo "$NETWORKS"|tr ' ,' ': ')

ZT_TOKEN=$(sudo cat $ZT_TOKEN_FILE)

if ! curl $CURL_ARGS -H "$ZT_TOKEN" https://my.zerotier.com/api/status|jq .online | grep -q true; then
    echo "Zerotier is offline. Aborting!"
    exit 1
fi

hosts=$(ansible "$inventory" -m command -b -a \
    'perl -e "open(IN, q[-|], q[zerotier-cli status]); while(<IN>) { if(s/^.*200 info ([0-9a-fA-F]+) .*$/$1/){print qq[RESULT;{{ inventory_hostname }};$_]} }"')

for network in $NETWORKS; do
    network_id=${network%%:*}
    for word in $hosts; do
        host=${word#RESULT;}
        if [[ $word == $host ]]; then
            continue
        fi
        hostname=${host%;*}
        host_id=${host#*;}
        curl -XPOST $CURL_ARGS \
            -H "$ZT_TOKEN" \
            -d '{"name": "'$hostname'", "config": {"authorized": true}}' \
            https://my.zerotier.com/api/network/${network_id}/member/${host_id} | jq .
    done
done
