#!/bin/bash
#
# A QAD script that disables general (but not host-specific) ssh access
# from the internet, whitelists a set of hosts (including the current
# ssh client IP) for ssh access, and attempts to replicate any existing
# public internet firewall holes on a set of secure networks.

# This assumes ufw.

# NETWORKS is a newline- or comma-separated list of network prefixes that are
# considered secure and which should have general access.

# WHITELIST is a newline- or comma-separated list of hosts that are considered
# secure and should have ssh access.

if [[ $(whoami) != "root" ]]; then
	# If we are not root, become root. Non-root invocation is necessary
	# because most methods of obtaining root reset the environment.
	# Duplicate any required envars on the other side of the sudo.
	exec sudo SSH_CONNECTION="${SSH_CONNECTION}" $0
fi

if [[ -d /etc/apt ]]; then
	APT=true
	SUDO=sudo
elif [[ -d /etc/yum ]]; then
	YUM=true
	SUDO=wheel
else
	echo "Distribution not supported!"
	exit -1
fi

NETWORKS=""
WHITELIST=""

if [[ -f /etc/ztlockdown ]]; then
	. /etc/ztlockdown
fi
if [[ -f ~/.ztlockdown ]]; then
	. ~/.ztlockdown
fi

# canonicalise
NETWORKS=$(echo "$NETWORKS"|tr ' ,' '_ ')
WHITELIST=$(echo "$WHITELIST"|tr ' ,' '_ ')

if [[ $APT ]]; then
  if [ ! -x /usr/sbin/ufw ]; then
	if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]; then
		apt-get update
	fi
	apt-get install ufw || exit 2
  fi
elif [[ $YUM ]]; then
  yum -y install ufw
fi

if ufw app info OpenSSH >&/dev/null ; then
  SSH_PROFILE="OpenSSH"
elif ufw app info SSH >&/dev/null ; then
  SSH_PROFILE="SSH"
else
  echo "SSH UFW profile not found. Aborting"
  exit 8
fi

remote_host=${SSH_CONNECTION%% *}
if [ ! ${remote_host} ]; then
	echo "Cannot whitelist current SSH connection. It is unsafe to continue."
	exit 3
fi

# Add the current remote host to the whitelist
WHITELIST="${remote_host} Autodetected ssh connection
${WHITELIST}"

# Now whitelist our friendly hosts BEFORE enabling ufw. Note that ufw
# maintains a latent configuration while disabled, but will not print
# it until after it has been enabled. This is evil and we must beware.

for host in $WHITELIST; do
	echo "Whitelisting ${host%% *} (${host#* })"

	### TODO: work out why the first invocation throws "ERROR: problem running"
	ufw allow to any app $SSH_PROFILE from "${host%% *}" comment "${host#* }" || echo "Retrying in case of CentOS stupidity..."
	ufw allow to any app $SSH_PROFILE from "${host%% *}" comment "${host#* }" || exit 3
done

# This is dangerous
yes | ufw enable

for network in $NETWORKS; do

	network_prefix=${network%% *}
	network_name=${network#* }

	echo "Adding ${network_prefix} (${network_name})"

	### TODO: use "ufw show added", which is more reliably parseable

	for i in $(ufw status | grep 'ALLOW\s*Anywhere' | grep -v '(v6)'); do
		UFW_TO=${i%ALLOW*}
		j=${i#*ALLOW}
		UFW_FROM=${j%\#*}
		if [[ "$UFW_FROM" != "$j" ]]; then
		    # there was a comment; preserve it
			UFW_COMMENT=${j#*\#}
		else
			UFW_COMMENT=""
		fi
		case "$UFW_TO" in
		22 )
			echo -n
			;;
		*\ on\ * )
			ufw allow from "$network_prefix" comment "($network_name) ${UFW_COMMENT}" || \
			ufw allow from "$network_prefix" comment "($network_name) ${UFW_COMMENT}"
			;;
		* )
			ufw allow from "$network_prefix" to "$UFW_TO" comment "($network_name) ${UFW_COMMENT}" || \
			ufw allow from "$network_prefix" to "$UFW_TO" comment "($network_name) ${UFW_COMMENT}"
			;;
		esac
	done

	# add ssh access anyway
	ufw allow from "$network_prefix" to any app $SSH_PROFILE comment "($network_name)" || \
	ufw allow from "$network_prefix" to any app $SSH_PROFILE comment "($network_name)"
	if [ -d /etc/sshguard ]; then
		echo "$network_prefix" >> /etc/sshguard/whitelist
	fi

done

# And try to delete all instances of generic ssh access
ufw delete allow $SSH_PROFILE
ufw delete allow 22
ufw delete allow 22/tcp

echo "Current firewall status - check for sanity"

# use -n to prevent delays
iptables -L -v -n
iptables -L -v -n -t nat
ufw status
