#!/bin/bash
#
# A QAD script to install zerotier and automatically join a list of networks
# We also optionally update the local /etc/hosts file

SCRIPT_DIR=$(dirname $(readlink -f $0))

if [[ -x $SCRIPT_DIR/apt-repo ]]; then
    ADMIN_TOOLS=$SCRIPT_DIR
else
    tempdir=$(mktemp -d)
    (cd $tempdir && git clone https://github.com/andrewgdotcom/admin-tools)
    ADMIN_TOOLS=$tempdir/admin-tools
fi

if [[ -d /etc/apt ]]; then
	APT=true
	SUDO=sudo
elif [[ -d /etc/yum ]]; then
	YUM=true
	SUDO=wheel
else
	echo "Distribution not supported!"
	exit -1
fi

# NETWORKS is a *newline-separated* list of zerotier networks to join
NETWORKS="8056c2e21c000001 world"

if [[ -f /etc/ztsetup ]]; then
	. /etc/ztsetup
fi
if [[ -f ~/.ztsetup ]]; then
	. ~/.ztsetup
fi

if [[ $APT ]]; then

  # Attempt to autodetect our distribution. This should work for debian and ubuntu
  # IFF the main distribution is configured sensibly
  DIST=$(grep ^deb.*main /etc/apt/sources.list|awk '{print $3}'|grep -v '-'|head -1)

  if zerotier-cli info 2>/dev/null; then
	echo "Already installed"
  else
    if [[ -x $SCRIPT_DIR/apt-repo ]]; then
        $SCRIPT_DIR/apt-repo add "http://download.zerotier.com/debian/$DIST $DIST main" https://zerotier.com/misc/contact@zerotier.com.gpg
    else
        apt-key --keyring /etc/apt/trusted.gpg.d/zerotier.gpg adv --keyserver pool.sks-keyservers.net --recv-key 1657198823E52A61
        cat > /etc/apt/sources.list.d/zerotier.list <<EOF
deb http://download.zerotier.com/debian/$DIST $DIST main
EOF
    fi
    apt-get update && apt-get -y install zerotier-one
  fi

elif [[ $YUM ]]; then

  DIST=$(yum repolist|grep ^base| awk '{print $2}')

  if [[ $DIST == "CentOS-7" || $DIST == "RHEL-7" ]]; then
    URL="https://download.zerotier.com/redhat/el/7"
  else
    echo "Distribution not supported!"
    exit -1
  fi

  cat <<EOF >/etc/yum.repos.d/zerotier.repo
[zerotier]
name=Zerotier for ${DIST}
baseurl=${URL}
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZEROTIER
EOF
  curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-ZEROTIER https://download.zerotier.com/contact%40zerotier.com.gpg
  yum -y install zerotier-one && service zerotier-one start

fi

while ! zerotier-cli info; do
	# Usually takes a moment for zerotier to become active
	sleep 1
done

IFS_SAVE="$IFS"
IFS="
"
# auto join the standard networks
for network in $NETWORKS; do
	network_id=${network%% *}
	zerotier-cli join $network_id
done
IFS=$IFS_SAVE

# and add some useful name resolutions
if [[ -f /etc/zthosts ]]; then
	cat /etc/zthosts >> /etc/hosts
fi
if [[ -f ~/.zthosts ]]; then
	cat ~/.zthosts >> /etc/hosts
fi

[[ -n "$tempdir" ]] && rm -rf "$tempdir"
