#!/bin/bash
#
# A QAD script to install zerotier and automatically join a list of networks
# We also optionally update the local /etc/hosts file

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
. $SCRIPT_DIR/poshlib/poshlib.sh || exit 1
use-from .
use swine
use apt-repo

if [[ -d /etc/apt ]]; then
	APT=true
	SUDO=sudo
elif [[ -d /etc/yum ]]; then
	YUM=true
	SUDO=wheel
else
	echo "Distribution not supported!"
	exit -1
fi

# NETWORKS is a comma-separated list of zerotier networks to join
# Comments are delimited by colons
NETWORKS="8056c2e21c000001:world"
# It can also be newline-separated, and/or with space-delimited comments
#NETWORKS=$'8056c2e21c000001 world\n0000000000000000 nowhere'

if [[ -f /etc/ztsetup ]]; then
	. /etc/ztsetup
fi
if [[ -f ~/.ztsetup ]]; then
	. ~/.ztsetup
fi

if [[ ${1:-} ]]; then
    NETWORKS="$1"
fi
# canonicalise
NETWORKS=$(echo "$NETWORKS"|tr ' ,' ': ')

if [[ ${APT:-} ]]; then

  # Attempt to autodetect our distribution. This should work for debian and ubuntu
  # IFF the main distribution is configured sensibly
  : ${DIST:=$(awk '/^deb.*main/ {print $3}' /etc/apt/sources.list | grep -v '-' | head -1)}

  if zerotier-cli info 2>/dev/null; then
	echo "Already installed"
  else
    apt-repo add zerotier "http://download.zerotier.com/debian/$DIST $DIST main" \
      https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg
    apt-get update && apt-get -y install zerotier-one
  fi

elif [[ ${YUM:-} ]]; then

  DIST=$(yum repolist | awk '/^base/ {print $2}')

  if [[ $DIST == "CentOS-7" || $DIST == "RHEL-7" ]]; then
    URL="https://download.zerotier.com/redhat/el/7"
  else
    echo "Distribution not supported!"
    exit -1
  fi

  cat <<EOF >/etc/yum.repos.d/zerotier.repo
[zerotier]
name=Zerotier for ${DIST}
baseurl=${URL}
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZEROTIER
EOF
  curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-ZEROTIER https://download.zerotier.com/contact%40zerotier.com.gpg
  yum -y --setopt=skip_missing_names_on_install=False install zerotier-one && service zerotier-one start

fi

while ! zerotier-cli info; do
	# Usually takes a moment for zerotier to become active
	sleep 1
done

# auto join the standard networks
for network in $NETWORKS; do
	network_id=${network%%:*}
	zerotier-cli join $network_id
done

# and add some useful name resolutions
if [[ -f /etc/zthosts ]]; then
	cat /etc/zthosts >> /etc/hosts
fi
if [[ -f ~/.zthosts ]]; then
	cat ~/.zthosts >> /etc/hosts
fi

if [[ -n "${tempdir:-}" ]]; then
    rm -rf "$tempdir"
fi
